"""CONSTANTS"""

CONST_WINDOW_WIDTH = 1152
CONST_WINDOW_HEIGHT = 648

CONST_PLAYER_SIZE = 44
CONST_GRAVITY = 0.6
CONST_JUMP_FORCE = -5.3
CONST_SPEED = 2.3

CONST_MAP_TILES_HEIGHT = 12
CONST_BLOCK_SIZE = 54
CONST_SPIKE_SIZE = 37